# Railway конфигурация для микросервисов

# Описание настроек для service-a
[builds.back-trip-app]
context = "app/back"
dockerfile = "back-trip-app/Dockerfile"
# Описание настроек для service-b
[builds.back-trip-manager]
context = "app/back"
dockerfile = "back-trip-manager/Dockerfile"
