name: Build Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: back-trip-app

    strategy:
      matrix:
        service: [back-trip-app, back-trip-manager]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Enable debug logs
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image for ${{ matrix.service }}
        working-directory: ./app/back
        run: |
          SERVICE_PATH="${{ matrix.service }}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/prod-app:${{ matrix.service }}-v1.1 -f $SERVICE_PATH/Dockerfile .

      - name: Verify Docker image built successfully
        run: docker images | grep "${{ matrix.service }}"

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/prod-app:${{ matrix.service }}-v1.1

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          SERVICE: ${{ matrix.service }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/prod-app:${{ matrix.service }}-v1.1
        run: |
          if [ "${{ matrix.service }}" == "back-trip-app" ]; then
            export RAILWAY_PROJECT=${{ secrets.RAILWAY_PROJECT_BACK_TRIP_MAIN_APP }}
          elif [ "${{ matrix.service }}" == "back-trip-manager" ]; then
            export RAILWAY_PROJECT=${{ secrets.RAILWAY_PROJECT_BACK_TRIP_MANAGER }}          
          fi
          railway up --service ${{ matrix.service }}-image

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ matrix.service }}-            
