name: Build Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: back-trip-app

    strategy:
      matrix:
        service: [ back-trip-app, back-trip-manager ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Enable debug logs
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        working-directory: ./app/back
        run: ./gradlew build --info

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image for ${{ matrix.service }}
        run: |
          BASE_PATH="app/back"
          SERVICE_PATH="$BASE_PATH/${{ matrix.service }}"
          cd $SERVICE_PATH
          docker build -t test-${{ matrix.service }}:latest .

      - name: Verify Docker image built successfully
        run: docker images | grep "test-${{ matrix.service }}"

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ matrix.service }}-            
